<?php
require_once 'config.php'; header('Content-Type: application/json');
function out($ok,$message='',$data=[]){echo json_encode(['success'=>$ok,'message'=>$message,'data'=>$data]);exit;}
function getCart($pdo){$cart=$_SESSION['cart']??[];$items=[];$total=0;$count=0;foreach($cart as $id=>$qty){$s=$pdo->prepare('SELECT id,name,price,image,stock FROM products WHERE id=? AND is_active=1');$s->execute([(int)$id]);$p=$s->fetch();if(!$p||$p['stock']<1){unset($_SESSION['cart'][$id]);continue;}$qty=min((int)$qty,(int)$p['stock']);$_SESSION['cart'][$id]=$qty;$sub=$p['price']*$qty;$total+=$sub;$count+=$qty;$items[]=['id'=>(int)$p['id'],'name'=>$p['name'],'price'=>(float)$p['price'],'image'=>$p['image'],'stock'=>(int)$p['stock'],'qty'=>$qty,'subtotal'=>(float)$sub];}return compact('items','total','count');}
$action=$_POST['action']??$_GET['action']??'';
if($action==='cart')out(true,'',getCart($pdo));
if($action==='add'){$id=(int)$_POST['product_id'];$qty=max(1,(int)($_POST['qty']??1));$s=$pdo->prepare('SELECT * FROM products WHERE id=? AND is_active=1');$s->execute([$id]);$p=$s->fetch();if(!$p)out(false,'Product not found.');$new=($_SESSION['cart'][$id]??0)+$qty;if($new>$p['stock'])out(false,"Only {$p['stock']} left in stock.");$_SESSION['cart'][$id]=$new;out(true,'Added to your order.',getCart($pdo));}
if($action==='update'){$id=(int)$_POST['product_id'];$qty=(int)$_POST['qty'];if($qty<=0)unset($_SESSION['cart'][$id]);else{$s=$pdo->prepare('SELECT stock FROM products WHERE id=? AND is_active=1');$s->execute([$id]);$p=$s->fetch();if(!$p)out(false,'Product unavailable.');if($qty>$p['stock'])out(false,"Only {$p['stock']} left in stock.");$_SESSION['cart'][$id]=$qty;}out(true,'Cart updated.',getCart($pdo));}
if($action==='remove'){unset($_SESSION['cart'][(int)$_POST['product_id']]);out(true,'Removed.',getCart($pdo));}
if($action==='checkout'){
 if(empty($_SESSION['cart']))out(false,'Your cart is empty.');$name=trim($_POST['name']??'');$email=trim($_POST['email']??'');if(!$name||!filter_var($email,FILTER_VALIDATE_EMAIL))out(false,'Enter a valid name and email.');
 try{$pdo->beginTransaction();$locked=[];$total=0;foreach($_SESSION['cart'] as $id=>$qty){$s=$pdo->prepare('SELECT * FROM products WHERE id=? AND is_active=1 FOR UPDATE');$s->execute([(int)$id]);$p=$s->fetch();if(!$p||$p['stock']<$qty)throw new Exception('Stock changed. Please review your cart.');$sub=$p['price']*$qty;$total+=$sub;$locked[]=['id'=>$p['id'],'name'=>$p['name'],'price'=>$p['price'],'qty'=>$qty,'subtotal'=>$sub];}$s=$pdo->prepare('INSERT INTO orders(user_id,customer_name,customer_email,total) VALUES(?,?,?,?)');$s->execute([$_SESSION['user_id']??null,$name,$email,$total]);$oid=$pdo->lastInsertId();$i=$pdo->prepare('INSERT INTO order_items(order_id,product_id,product_name,price,quantity,subtotal) VALUES(?,?,?,?,?,?)');$u=$pdo->prepare('UPDATE products SET stock=stock-? WHERE id=?');foreach($locked as $x){$i->execute([$oid,$x['id'],$x['name'],$x['price'],$x['qty'],$x['subtotal']]);$u->execute([$x['qty'],$x['id']]);}$pdo->commit();$_SESSION['cart']=[];out(true,'Order placed.', ['order_id'=>$oid]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();out(false,$e->getMessage());}}
out(false,'Invalid action.');
